apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: inpl-staging-cluster1
  region: eu-west-1

# VPC with public and private subnets
vpc:
  subnets:
    private:
      eu-west-1a:
        id: subnet-0dfeb8f42d29493bb # Private subnet in AZ eu-west-1a
      eu-west-1b:
        id: subnet-08f6ac48cc8fcd42d # Private subnet in AZ eu-west-1b
    public:
      eu-west-1a:
        id: subnet-07779ee8929ac5dc7 # Public subnet in AZ eu-west-1a
      eu-west-1b:
        id: subnet-0b649f7f96b70a062 # Public subnet in AZ eu-west-1b

# creates managed node group
managedNodeGroups:
  - name: default-managed-workers
    instanceType: t3.medium
    desiredCapacity: 4
    minSize: 3
    maxSize: 7
    privateNetworking: true # Ensures the nodes are created in private subnets
    subnets:
      - subnet-0dfeb8f42d29493bb
      - subnet-08f6ac48cc8fcd42d
