apiVersion: v1
kind: Secret
metadata:
  name: aws-ssm-credentials
  namespace: default
type: Opaque
data:
  accessKey: "" # <== Input Base64-encoded AWS AccessKey and rename this file without sample
  secretKey: "" # <== Input Base64-encoded AWS SecretKey and rename this file without sample
