{{- range .Values.casinoApplications }}
{{- range .services }}

  {{- $service := . }}# Capture the current service configuration
  {{- if and $service.hpa.enabled (gt $service.hpa.maxReplicas $service.hpa.minReplicas) }}
    {{- range .applications }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $.Release.Name }}-{{ .name }}-hpa
  namespace: default
  labels:
    app: {{ $.Release.Name }}-{{ .name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $.Release.Name }}-{{ .name }}-deployment
  minReplicas: {{ $service.hpa.minReplicas }}
  maxReplicas: {{ $service.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $service.hpa.targetCPUUtilizationPercentage }}
    {{- if $service.hpa.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $service.hpa.targetMemoryUtilizationPercentage }}
    {{- end }}
---
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
