apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secrets-store-csi-driver-role
rules:
  - apiGroups: ["storage.k8s.io"]
    resources: ["csidrivers"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["", "storage.k8s.io", "apps", "networking.k8s.io"]
    resources: ["events", "pods"]
    verbs: ["create", "update", "patch"]
