{{- if .Values.secretProviderClass }}

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProviderClass.name }}
  namespace: {{ .Values.secretProviderClass.namespace }}
spec:
  provider: {{ .Values.secretProviderClass.provider }}
  parameters:
    objects: |
      {{- range .Values.secretProviderClass.secrets }}
        {{- range .parameters }}
      - objectName: "{{ .objectName }}"
        objectType: "{{ .objectType }}"
        objectAlias: "{{ .key }}"
      {{- end }}
      {{- end }}
  secretObjects:
    {{- range .Values.secretProviderClass.secrets }}
    - secretName: {{ .name }}
      type: {{ .type }}
      data:
        {{- range .parameters }}
        - key: {{ .key }}
          objectName: "{{ .key }}"
        {{- end }}
    {{- end }}
{{- end }}
